### ISSUE TITLE
emsg duration information is missing

### ISSUE THREAD

**Issue by RufaelDev** [AOMediaCodec/id3-emsg#23]
The specification uses 'emsg' to carry id3 but not all fields are defined, especially those related to timing.  I outline my questions related to the timing with suggested answers.

what should the duration of the emsg version 1 be ? 
=> if emsg is send with each fragment it may be the fragment duration in each case
=> in case the duration is just the time for which the metadata applies this should be mentioned 
=> if the duration is indefenete/unknown this should be mentioned and het duration must be set to 0xFFFFFFFF

**Comment by cconcolato** [comment]
The group discussed the issue and agreed to add additional text along the following lines in https://aomediacodec.github.io/av1-id3/#semantics:

> In general, id3 don't carry a duration and in those cases the emsg duration field should be set to 0xFFFFFFFF. If in a particular case, the id3 message carries a duration, it should be reflected in the emsg box.

Editors to add.
