### ISSUE TITLE
emsg presentation_time usage is undefined

### ISSUE THREAD

**Issue by RufaelDev** [AOMediaCodec/id3-emsg#24]
what should the constraints on presentation time of the emsg version 1 be ?

=> is it allowed to send metadata that applies to a later or earlier fragment ? 

=> I would recommend the presentation time to be the earliest presentation time of the fragment, or at least to overlap with the fragment it is send with. 
=> if this is not the case it should be explicitly mentioned what the presentation time could be in the specification

**Comment by cconcolato** [comment]
The group discussed the issue. 

Random access requires repeating the message in multiple segments, or event within the segment (low latency case).

The group agrees to add:
> The presentation time must be within the time interval of the fragment.

Editors to implement.
