### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by Ricardo1980** [AOMediaCodec/id3-emsg#39]
Here:
https://aomediacodec.github.io/id3-emsg/
The link to ID3 is not working:
[ID3]
ID3.org, “The ID3 audio file data tagging format”, http://www.id3.org/Developer_Information.

It says: "No wiki configuration matching the URL found!"

**Comment by shaunflagg** [comment]
This is the link https://id3.org/Developer%20Information - there is space instead of underscore
